AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: MyAssembly::MyNamespace.MyClass::MyMethod
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: dotnet6
      Code:
        S3Bucket: cloudformation-lambda-28032024
        S3Key: dotnet-hello-world-master.zip
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - S3:*
                  - dynamodb:*
                  - connect:*
                Resource: "*"
  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyRestApi}/*/*"
  MyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyAPIGateway
  MyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyRestApi
      ParentId: !GetAtt MyRestApi.RootResourceId
      PathPart: "{proxy+}"
  ANYMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      ResourceId: !Ref MyResource
      RestApiId: !Ref MyRestApi
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200
  OptionMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      ResourceId: !Ref MyResource
      RestApiId: !Ref MyRestApi
      Integration:
        Type: MOCK
        IntegrationHttpMethod: POST
  MyDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
    - ANYMethod
    - OptionMethod
    Properties:
      RestApiId: !Ref MyRestApi
  MyApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref MyDeployment
      RestApiId: !Ref MyRestApi
      StageName: dev





