Resources:
 OriginAccessControl:
  Type: AWS::CloudFront::OriginAccessControl
  Properties:
   OriginAccessControlConfig: 
    Name: Orgin-Access-Control 
    OriginAccessControlOriginType: s3
    SigningBehavior: always
    SigningProtocol: sigv4



     
    
 